メモアプリの作成
Yatsu0720/memo pull request #1
Opened 2022-06-29 15:15 UTC by Yatsu0720

Sinatraを使ってメモアプリを作成しました｡READMEも含め、確認お願いいたします！

2022-07-05 09:46 UTC, func09 requested changes
ひとまずレビューしました。
アプリの起動ができなかったので、
起動できるように再提出をお願いします！

2022-07-05 09:46 UTC, func09 commented on README.md
> +`bundle exec ruby memo_app.rb`
リポジトリを clone して 実行したところ下記のようなエラーとなり動作しませんでした。

```
% bundle exec ruby memo_app.rb
Could not locate Gemfile or .bundle/ directory
```

必須条件にある

> Bundlerを使って必要なGemをインストールする手順になっていること

を満たすようにファイル構成やセットアップ手順を変更してください 🙏

2022-07-05 09:46 UTC, func09 commented on memo_app.rb
> +    JSON.load(file)
> 厳密にはセキュリティ的にはloadよりparseの方が望ましいとのことでしたが、今回のプラクティスでそこまで反映させる必要がありますでしょうか？

こちらは rubocopに従って、 `parse` を利用する方式にして提出おねがいしますー。

2022-07-11 03:55 UTC, func09 requested changes

2022-07-11 03:55 UTC, func09 commented on README.md
> +`bundle exec ruby memo_app.rb`
この指示の前に `bundle install` が必要なので
その手順も書いておいてもらえると 👍 です

2022-07-11 03:55 UTC, func09 commented on views/edit.erb
> +<html lang="ja">
例えば編集画面のHTMLソースを確認すると

```
<html>
  ...（省略）
  <html>
  </html>
</html>
```

のように `html` が入れ子になってしまっています。
Sinatraのドキュメントでレイアウトとビューの関係を再確認してみてください〜

2022-07-11 03:55 UTC, func09 commented on views/index.erb
> +<html lang="ja">
ここもHTMLが入れ子になってしまっています

2022-07-11 03:55 UTC, func09 commented on views/memo.erb
> +<html lang="ja">
ここも同様です

2022-07-11 03:55 UTC, func09 commented on views/new_memo.erb
> +<html>
ここも同様です

2022-07-11 03:55 UTC, func09 commented on memo_app.rb
> +get '/memo' do
この URLは何用でしょうか？
不要そうに見えました

2022-07-11 03:55 UTC, func09 commented on memo_app.rb
> +get '/memo/:name/edit' do
他のURL設計全体が RESTful になっていないなと思いました。
RESTの考え方を思い出して、再設計してみてください。

例えば

```
GET /memos
GET /memos/:id
```

こういう感じになるように再設計できますか？

2022-07-14 07:13 UTC, Yatsu0720 commented
以下の点につきまして訂正いたしました｡
・viewファイルとlayoutで重複しているhtmlコードを統合
・RESTに合致するようにURLを修正
・その他、不必要な部分を削除

2022-07-14 09:45 UTC, func09 requested changes
レビューしましたー。

* レイアウトと各ビューの入れ子状態はなおっていました。
* REST的なURLは一部修正の必要ありでした。

---

* REST的になっていないURLの指摘
* JSONの構造化の指摘

など、ご確認ください

2022-07-14 09:45 UTC, func09 commented on memo_app.rb
> +    JSON.parse(file.read)
🙆‍♀️

2022-07-14 09:45 UTC, func09 commented on memo_app.rb
> +  @json_data = File.open('memo_data.json') do |file|
'memo_data.json' が何回も出てくるので定数にすることをオススメします。

2022-07-14 09:45 UTC, func09 commented on memo_app.rb
> +  @memo_id = params[:id]
ここの３行の変数って使っていますか？
定義している理由がわからなかったので
使っていないなら削除、使っているなら解説をお願いしますー

2022-07-14 09:45 UTC, func09 commented on memo_app.rb
> +get '/' do
SHOW, EDIT, DELETE, UPDATE は REST風なURLになったと思うのですが

* LIST（一覧）
* NEW（新規）
* CREAT（作成）

が RESTになりきっていないようです。

他のURLが `/memos/xxxx` のような形式なので、それに合わせてみてください。

2022-07-14 09:45 UTC, func09 commented on memo_app.rb
> +post '/' do
上でも書きましたが、ここも memos の REST的なURLにお願いします

2022-07-14 09:45 UTC, func09 commented on memo_app.rb
> +  @memo_title = @json_data.fetch(@memo_id).keys[0]
```json
{
   "20220714181653657552000":{
      "もうひとつメモです":"めもだよめもだよ"
   },
   "20220714183239237110000":{
      "こんにちわタイトル":"こんにちわ本文"
   }
}
```

今はこんな感じのデータ構造になっているようですが、保存する項目が増えた時に困りそうだなと思いました。

```json
{
   "20220714181653657552000":{
      "title": "もうひとつメモです",
      "body": "めもだよめもだよ",
   },
   "20220714183239237110000":{
      "title": "こんにちわタイトル",
      "body": "こんにちわ本文",
   }
}
```

せっかくJSONを使っているので構造化されたデータにした方が良さそうです。
そうすれば

```ruby
@memo = @json_data[@memo_id]
@memo_title = @memo["title"]
```

というような書き方で取得することができますよ。

2022-07-14 09:45 UTC, func09 commented on memo_app.rb
> +patch '/memos/:id/edit' do
PUTやPATCHでリソースを更新する場合は

```
PATCH /memos/:id
```

こんな感じでリソースURLとHTTPメソッドだけで表現できるので `edit` の部分は不要ですよ。

2022-07-15 09:13 UTC, Yatsu0720 commented on memo_app.rb
> +  @json_data = File.open('memo_data.json') do |file|
定数として定義しました｡

2022-07-15 09:14 UTC, Yatsu0720 commented on memo_app.rb
> +  @memo_id = params[:id]
おそらく初期の段階で試行錯誤していたものが残ってしまっていたと思われます💦
削除しました｡

2022-07-15 09:19 UTC, Yatsu0720 commented on memo_app.rb
> +  @memo_title = @json_data.fetch(@memo_id).keys[0]
他の方のQ&Aなどを見て、本当は下の方が綺麗な構造だなあと思いつつ、問題なく動いていたので妥協してしまっていました汗　構造化しました｡

2022-07-15 09:20 UTC, Yatsu0720 commented on memo_app.rb
> +patch '/memos/:id/edit' do
言われてみるとたしかにそうですね汗
修正いたしました｡

2022-07-17 00:55 UTC, func09 requested changes
rubocop を通してみたところ

> 1 file inspected, 17 offenses detected, 15 offenses autocorrectable

でした。自動修正が効くものもあれば、手で直す必要があるコードもあったので
確認おねがいします！

2022-07-17 00:55 UTC, func09 commented on memo_app.rb
> +  open(MEMO_DATA, 'w') do |file|
ここは セキュリティ的に rubocop が通らなくなっていると思います。
最後に rubocop のチェックをお願いします〜

> Security/Open: The use of Kernel#open is a serious security risk.

2022-07-17 00:57 UTC, func09 requested changes

2022-07-17 00:57 UTC, func09 commented on memo_app.rb
> +MEMO_DATA = 'memo_data.json'
👍

2022-07-17 00:57 UTC, func09 commented on memo_app.rb
> +  @memo_body = @memo["body"]
同じ処理を２回やってるようですね。
不要な行は削りましょう

2022-07-18 09:32 UTC, func09 approved these changes
rubocopにもちゃんと通っていることを確認できました、バッチリです！
LGTM 🎉🎉

2022-07-22 05:04 UTC, merged